n1 = input("Digite seu nome: ")
n2 = input("Digite sua idade: ")
n3 = input("Digite seu email: ")
n4 = input("Digite sua data de nascimento: ")
n5 = input("Digite seu telefone: ")
print("-------------------------------------------------------------------------------------------")
print("----------------------------------------informações----------------------------------------")
print("-------------------------------------------------------------------------------------------")
print("O nome informado foi: ", n1)
print("A idade informada foi: ", n2)
print("O email informado foi: ", n3)
print("A data de nascimento informada foi: ", n4)
print("O telefone informado foi: ", n5)